export type stunicon = 'si-activity' |
 'si-alarm-warning' |
 'si-alert' |
 'si-align-justify' |
 'si-align-left' |
 'si-align-right' |
 'si-apps' |
 'si-archive' |
 'si-arrow-down-fill' |
 'si-arrow-down' |
 'si-arrow-left' |
 'si-arrow-right' |
 'si-arrow-up-fill' |
 'si-arrow-up' |
 'si-award' |
 'si-behance' |
 'si-bookmark' |
 'si-briefcase-2' |
 'si-briefcase' |
 'si-calendar' |
 'si-camera' |
 'si-chart-1' |
 'si-chat-history' |
 'si-check' |
 'si-chevron-down' |
 'si-chevron-left' |
 'si-chevron-right' |
 'si-chevron-up' |
 'si-close' |
 'si-cloud' |
 'si-contrast' |
 'si-copyright' |
 'si-dashboard' |
 'si-delete' |
 'si-document' |
 'si-dollar-sign' |
 'si-download' |
 'si-dribbble' |
 'si-edit' |
 'si-error' |
 'si-exit-full-screen' |
 'si-exit' |
 'si-eye' |
 'si-facebook' |
 'si-file-list' |
 'si-flag' |
 'si-flash' |
 'si-folder' |
 'si-full-screen' |
 'si-git-branch' |
 'si-github' |
 'si-globe' |
 'si-gmail' |
 'si-heart' |
 'si-home' |
 'si-honour' |
 'si-image' |
 'si-info' |
 'si-instagram' |
 'si-label' |
 'si-layers' |
 'si-link' |
 'si-linkedin' |
 'si-location-off' |
 'si-location-on' |
 'si-lock' |
 'si-menu-alt' |
 'si-menu-bar' |
 'si-message' |
 'si-mic' |
 'si-moon' |
 'si-more-horizontal' |
 'si-more-vertical' |
 'si-movie' |
 'si-mute' |
 'si-open-door' |
 'si-organisation-chart' |
 'si-paper-clip' |
 'si-pause' |
 'si-phone-2' |
 'si-phone' |
 'si-pie-chart-2' |
 'si-play-1' |
 'si-play-2' |
 'si-plus-2' |
 'si-plus' |
 'si-printer' |
 'si-pushpin' |
 'si-reply' |
 'si-restart' |
 'si-search' |
 'si-selector' |
 'si-send-1' |
 'si-send-2' |
 'si-settings' |
 'si-share' |
 'si-shopping-bag' |
 'si-shopping-cart' |
 'si-slack' |
 'si-speaker' |
 'si-star' |
 'si-tag' |
 'si-thumbs-down' |
 'si-thumbs-up' |
 'si-time' |
 'si-tv' |
 'si-twitter' |
 'si-upload-2' |
 'si-upload' |
 'si-user' |
 'si-users-2' |
 'si-users' |
 'si-video' |
 'si-window' |
 'si-youtube' |
 'si-zoom-in' |
 'si-zoom-out'